export const ORDER_THEME = {
  background: '#FFF8EF',
  backgroundAlt: '#FFFBF7',
  surface: '#FFFFFF',
  surfaceSoft: '#FFF3EB',
  border: '#E8D5C4',
  borderSoft: '#F5EBE1',
  textPrimary: '#3A2113',
  textSecondary: '#8B7E74',
  textMuted: '#B0A498',
  accent: '#FF7A30',
  accentSoft: '#FFF3E9',
  success: '#2ECC71',
  successSoft: '#E6F7ED',
  warning: '#F5A623',
  warningSoft: '#FFF3E0',
  danger: '#E74C3C',
  dangerSoft: '#FDECEC',
  info: '#4A90E2',
  infoSoft: '#E8F1FC',
};
